name: Hyceate's Live2D Portfolio
author: Hyceate
url: https://hyceate.pages.dev
favicon: /img/favicon.jpg
keywords:
  - hyceate
  - youtuber
  - live2d
  - artist
  - rigger
  - 2d
  - animation
  - commissions
  - freelancer
  - illustrator
  - hire
  - commission
  - anime
  - japan
